# Use Node.js image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy frontend files
COPY . .

# Install dependencies
RUN npm install

# Expose React frontend port
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
